export default {
  HeroHeading: 'AI Logo Maker',
  HeroSubheading: 'Perfect Logos for Apps, Businesses, and Websites',
  HeroDesc: 'Craft unique and professional logos effortlessly with our AI-powered tool. Perfect for apps, businesses, websites, and more!',
  InputTitlePlaceholder: 'Enter your Logo Name',
  LogoTitle: 'Logo Title',
  LogoTitleDesc: 'Add Your Bussiness, App, or Website Name for a Custom Logo',
  InputDescPlaceholder: 'Logo Description',
  LogoDescTitle: 'Describe Your Logo Version',
  LogoDescDesc: 'Share your ideas, themes, or inspiration to create a unique logo that perfectly represents your brand or project.',
  LogoColorPaletteTitle: 'Choose Your Color Palette',
  LogoColorPaletteDesc: 'Pick the colors that reflect your brands personality and create a lasting impression.',
  LogoDesignTitle: 'Choose Your Logo Style',
  LogoDesignDesc: 'Select the type of logo design that best represents your brand.',
  LogoIdeaTitle: 'Select Your Design Idea',
  LogoIdeaDesc: 'Choose a design style that aligns with you version, or',
}